In [1]:
import numpy as np

In [3]:
n_vars = 5
i = np.linspace(1,n_vars,n_vars)
j = np.linspace(1,n_vars,n_vars)

In [4]:
alpha = 5
K = lambda s,t: np.exp(-1*(s-t)**2/alpha)
decay = K(i[:,None], j[None,:])

In [5]:
decay

array([[1.        , 0.81873075, 0.44932896, 0.16529889, 0.0407622 ],
       [0.81873075, 1.        , 0.81873075, 0.44932896, 0.16529889],
       [0.44932896, 0.81873075, 1.        , 0.81873075, 0.44932896],
       [0.16529889, 0.44932896, 0.81873075, 1.        , 0.81873075],
       [0.0407622 , 0.16529889, 0.44932896, 0.81873075, 1.        ]])

In [6]:
Q  = np.random.randn(n_vars, n_vars)
print(Q)

[[ 0.31121658 -0.57366826  0.44053904  0.79001079  0.14945572]
 [ 0.19932318 -1.14881813 -0.73797069  2.08922317  1.74994914]
 [ 0.51987358 -1.2918637  -2.10773808 -1.21962912  0.35629498]
 [-0.013726    0.96579849 -2.33342558 -0.53669749 -0.63985531]
 [ 1.30949654  0.72152244  0.92857659  0.34173534 -0.48018302]]


In [7]:
Qa = Q*decay
Qa

array([[ 0.31121658, -0.46967985,  0.19794695,  0.1305879 ,  0.00609214],
       [ 0.16319202, -1.14881813, -0.6041993 ,  0.93874848,  0.28926465],
       [ 0.23359426, -1.05768854, -2.10773808, -0.99854787,  0.16009365],
       [-0.00226889,  0.43396124, -1.91044729, -0.53669749, -0.52386922],
       [ 0.05337797,  0.11926686,  0.41723636,  0.27978923, -0.48018302]])